import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import benjampo from './../assets/images/benjampo.png';
import ProjectCard from '../components/ProjectCard';
import Projects from '../data/projects';
import Link from 'next/link';
import React from 'react';
const Home: NextPage = () => {
    return (
        <div className="px-6">
            <Head>
                <title>Benjampo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section>
                <Image src={benjampo} />
                <span className="block m-auto font-bold text-5xl text-center">Hello World</span>
                <h1 className="font-semibold text-2xl text-center text-gray-400">
                    I’m Benjamin Front-End developper
                </h1>
            </section>
            <section>
                <ul className="grid md:grid-flow-col md:grid-cols-4  md:grid-rows-3  gap-4 md:grid-flow-row ">
                    {Projects.filter((project, index) => {
                        return index < 8;
                    }).map((project: any, index) =>
                        [1, 2, 6, 4].includes(index) ? (
                            <ProjectCard
                                row={''}
                                span={'md:col-span-2'}
                                key={project.id}
                                project={project}
                            />
                        ) : (
                            <ProjectCard row={''} span={''} key={project.id} project={project} />
                        )
                    )}
                </ul>
            </section>
        </div>
    );
};

export default Home;
